### ISSUE TITLE
Not able to access the NEU surface defect database

### ISSUE THREAD

**Issue by mehuls45** [abin24/Surface-Inspection-defect-detection-dataset#1]
I am using the link given in the README to access the surface defect database (http://faculty.neu.edu.cn/me/songkc/Vision-based_SIS_Steel.html). But for some reason, I am not able to access it. Can someone point me to another link to download this dataset or if a local copy is available can I get a link to it?

**Comment by abin24** [comment]
------------------ 原始邮件 ------------------
发件人: "Mehul Solanki"<notifications@github.com>;
发送时间: 2019年3月20日(星期三) 中午1:04
收件人: "abin24/Surface-Inspection-defect-detection-dataset"<Surface-Inspection-defect-detection-dataset@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [abin24/Surface-Inspection-defect-detection-dataset] Not able toaccess the NEU surface defect database (#1)




I am using the link given in the README to access the surface defect database (http://faculty.neu.edu.cn/me/songkc/Vision-based_SIS_Steel.html). But for some reason, I am not able to access it. Can someone point me to another link to download this dataset or if a local copy is available can I get a link to it?

**Comment by mehuls45** [comment]
The link is now working. Thank you so much :)

**Comment by GewelsJI** [comment]
Can not access to the surface defect database (http://faculty.neu.edu.cn/me/songkc/Vision-based_SIS_Steel.html). Could you help me? @abin24
